name: aws ec2 deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: deploy pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v3 
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.R_PKP }}
        REMOTE_HOST: ${{ secrets.R_HOST }}
        REMOTE_USER: ${{ secrets.R_USER }}
        REMOTE_PORT: ${{ secrets.R_PORT }}
        TARGET: /var/www/prajwal-scorpionking123.github.io
